### ISSUE TITLE
Can't obtain .deb package

### ISSUE THREAD

**Issue by jin146** [chalaev/wifi-switcher#1]
Hi ! 
As the website has been down for a while, the .deb package's link in the readme is dead.

By the more, I can't use the pack.sh script, as some ressources appear to be absent (dependencies ?) : 

```
$ sh pack.sh
find: ‘/srv/local-apt-repository/’: No such file or directory
rm: cannot remove '../wifi-switcher_*': No such file or directory
pack.sh: 1: pack.sh: dpkg-parsechangelog: not found
Packaging the th version.
mv: cannot stat '.pc': No such file or directory
pack.sh: 46: pack.sh: dh_make: not found
mv: cannot stat '../wifi-switcher.pc': No such file or directory
pack.sh: 53: pack.sh: dpkg-buildpackage: not found
pack.sh: 60: pack.sh: debsign: not found
```

**Comment by chalaev** [comment]
The files are now available here:
https://github.com/chalaev/chalaev/tree/master/pub/ws/

Note that you will have to specify your wifi interface
manually in the following files:
/etc/default/wifi-switcher
and
/etc/sudoers.d/wifi-switcher

The interface name can be obtained from the command
ip addr ls

For example, in my case it is wlx503eaa8af16e.

So my files

/etc/default/wifi-switcher
and
/etc/sudoers.d/wifi-switcher

contain the following lines:

** /etc/default/wifi-switcher **
wifi_interface="wlx503eaa8af16e"

** /etc/sudoers.d/wifi-switcher **
%netdev ALL=NOPASSWD:/sbin/iwlist wlx503eaa8af16e scan
%netdev ALL=NOPASSWD:/sbin/ifdown wlx503eaa8af16e
%netdev ALL=NOPASSWD:/sbin/ifup wlx503eaa8af16e=wifiswitcher

Best regards,
Oleg

**Comment by jin146** [comment]
Thank you very much for the files and the detailed informations !

**Comment by chalaev** [comment]
Update: in wifi-switcher_2.0-1_all.deb wireless interface name should be automatically determined, so one does not need to edit configuration files.
